# @package _global_

defaults:
  - ../env: null  # Please specify environment to use in command line
  - ../method: cqn
  - ../reward_method: hybrid

env:
  reward_mode: initial

pixels: false
frame_stack: 1
action_repeat: 1

batch_size: 256
update_every_steps: 1
replay:
  size: 7000000
  nstep: 3  # Use 1 for walker_walk
num_train_frames: 7001000
save_snapshot: true
eval_every_steps: 20000
snapshot_every_n: 50000
num_explore_steps: 10000
replay_size_before_train: 10000

reward_method:
  data_aug_ratio: 20

method:
  critic_lr: 5e-5
  view_fusion_lr: 5e-5
  encoder_lr: 5e-5
  use_dueling: false
  weight_decay: 0.1
  stddev_schedule: 0.01
  advantage_model:
    keys_to_bottleneck: [fused_view_feats, low_dim_obs, time_obs]
  value_model:
    keys_to_bottleneck: [fused_view_feats, low_dim_obs, time_obs]

rlhf:
  use_rlhf: true
  feedback_type: gemini
  comparison_type: sequential
  query_type: random
  max_feedback: 200
  update_every_steps: 50000
  num_pretrain_steps: 50000
  num_train_frames: 500
  initialize_agent_per_session: true
  initialize_reward_model_per_session: true
  snapshot_every_n: ${rlhf.update_every_steps}
  gemini:
    model_type: gemini-1.5-pro
    target_viewpoints: ${env.query_keys}

rlhf_replay:
  num_queries: 20
  num_labels: 1
  seq_len: 30
  feedback_batch_size: 128
  max_episode_number: 500

hydra:
  run:
    dir: ./exp_local/state_cqn_rlhf/locomujoco_${env.task_name}/rlhf_hybrid_${rlhf.feedback_type}_numf${rlhf.max_feedback}_numq${rlhf_replay.num_queries}_update${rlhf.update_every_steps}_pretrain${rlhf.num_pretrain_steps}_comp-${rlhf.comparison_type}_reward-reset-${rlhf.initialize_reward_model_per_session}_agent-reset-${rlhf.initialize_agent_per_session}_lambda${reward_method.lambda_weight}_sc-${rlhf.gemini.compute_self_consistency}_sc-temp${rlhf.gemini.self_consistency_temperature}_sc-n${rlhf.gemini.n_self_consistency_samples}_seed${seed}_${now:%Y%m%d%H%M%S}
