# @package _global_

defaults:
  - ../env: null  # Please specify environment to use in command line
  - ../method: cqn

pixels: false
frame_stack: 1
action_repeat: 1

demos: 25
min_max_margin: 0.1

batch_size: 256
demo_batch_size: 256
replay:
  size: 1000000
  nstep: 3  # Use 1 for walker_walk
  num_workers: 4
  demo_size: 30000

num_train_frames: 1000100
num_pretrain_steps: 0
num_explore_steps: 0
replay_size_before_train: 1000
update_every_steps: 1
save_snapshot: true
eval_every_steps: 10000
snapshot_every_n: 1000000
visual_observation_shape: [128, 128]

method:
  critic_lr: 5e-5
  view_fusion_lr: 5e-5
  encoder_lr: 5e-5
  weight_decay: 0.1
  bc_lambda: 1.0
  bc_margin: 0.01
  use_dueling: true
  stddev_schedule: 0.01
  v_min: 0.0
  v_max: 200.0
  atoms: 51
  always_bootstrap: true
  critic_lambda: 0.1
  advantage_model:
    keys_to_bottleneck: [fused_view_feats, low_dim_obs, time_obs]

  value_model:
    keys_to_bottleneck: [fused_view_feats, low_dim_obs, time_obs]

hydra:
  run:
    dir: ./exp_local/state_cqn/locomujoco_${env.task_name}_${now:%Y%m%d%H%M%S}
