# @package _global_

defaults:
  - ../env: null  # Please specify environment to use in command line
  - ../method: cqn_simple

pixels: false
frame_stack: 1
action_repeat: 1

batch_size: 256
update_every_steps: 1
replay:
  size: 1000000
  nstep: 3  # Use 1 for walker_walk
num_train_frames: 1000100
num_explore_steps: 10000
replay_size_before_train: 10000
save_snapshot: true
eval_every_steps: 20000
snapshot_every_n: 100000

method:
  critic_lr: 5e-5
  view_fusion_lr: 5e-5
  encoder_lr: 5e-5
  use_dueling: false
  stddev_schedule: 0.01
  advantage_model:
    keys_to_bottleneck: [fused_view_feats, low_dim_obs, time_obs]
  value_model:
    keys_to_bottleneck: [fused_view_feats, low_dim_obs, time_obs]
  critic_target_interval: 1000
  critic_target_tau: 1.0

hydra:
  run:
    dir: ./exp_local/state_cqn/locomujoco_${env.task_name}_${now:%Y%m%d%H%M%S}
