# @package _global_

defaults:
  - ../env: null
  - ../method: dreamerv3

pixels: false
frame_stack: 1
batch_size: 16
replay_size_before_train: 2500
update_every_steps: 2
num_explore_steps: 2500
frame_stack_on_channel: false
eval_every_steps: 5000

dynamics_model:
  deter: 1024

pixel_encoder_model:
  channels: 48

pixel_decoder_model:
  channels: 48

replay:
  sequential: true
  num_workers: 4
  gamma: 0.997
  size: 500000
  transition_seq_len: 64  # the length of transition seq for each sample

hydra:
  run:
    dir: ./exp_local/state_dreamerv3/humanoidbench_${env.task_name}/default_seed${seed}_${now:%Y%m%d%H%M%S}
