# @package _global_
# DrQ-v2+ baseline introduced in CQN paper

defaults:
  - ../method: drqv2
  - ../reward_method: preference_transformer
  - ../env: null

pixels: true
visual_observation_shape: [84, 84]
frame_stack: 8
action_repeat: 1

demos: 50
use_min_max_normalization: true
min_max_margin: 0
norm_obs: true
use_standardization: false
batch_size: 256
demo_batch_size: 256
num_pretrain_steps: 0
num_explore_steps: 0
replay_size_before_train: 500
use_self_imitation: true
num_train_frames: 100100

num_eval_episodes: 5
eval_every_steps: 2000

update_every_steps: 1
replay:
  nstep: 1
  size: 50000
  demo_size: 50000
  num_workers: 0
  save_snapshot: true

rlhf:
  use_rlhf: true
  feedback_type: random
  comparison_type: sequential_pairwise
  query_type: random
  max_feedback: 2000
  update_every_steps: 2500
  num_pretrain_steps: 200
  num_train_frames: 200
  snapshot_every_n: 2500

rlhf_replay:
  num_queries: 50
  num_labels: 1
  seq_len: 50
  feedback_batch_size: 16

method:
  bc_lambda: 1.0
  stddev_schedule: 0.01
  weight_decay: 0.1
  always_bootstrap: true
  distributional_critic: true
  distributional_critic_limit: 2
  distributional_critic_atoms: 101
  distributional_critic_transform: false

  critic_model:
    output_shape: [101, 1]

  encoder_model:
    kernel_size: 4
    padding: 1
    channels_multiplier: 2
    num_downsample_convs: 4
    num_post_downsample_convs: 0

log_every: 50
log_pretrain_every: 50
log_eval_video: true

hydra:
  run:
    dir: ./exp_local/pixel_drqv2+/bigym-${env.task_name}-pt-feedback_${rlhf.feedback_type}-comp_${rlhf.comparison_type}-query_${rlhf.query_type}-${rlhf_replay.num_queries}q-${rlhf.max_feedback}max-${rlhf.update_every_steps}interact-seed${seed}-${now:%Y%m%d%H%M%S}
