# @package _global_

defaults:
  - ../env: null  # Please specify environment to use in command line
  - ../method: ppo
  - ../reward_method: hybrid

env:
  reward_mode: initial

pixels: false
frame_stack: 1
action_repeat: 1
num_train_envs: 32
update_every_steps: 1
num_eval_episodes: 5
log_every: 1
eval_every_steps: 30
save_snapshot: true
snapshot_every_n: 30
num_train_frames: 10001000

method:
  learning_rate: 1.0e-4
  gamma: 0.99
  desired_kl: 0.02
  actor_hidden_dims: [256, 128, 64]
  critic_hidden_dims: [256, 128, 64]
  activation: elu
  entropy_coef: 0.001

reward_method:
  data_aug_ratio: 20
  lambda_weight: 0.1

rlhf:
  use_rlhf: true
  feedback_type: gemini
  comparison_type: major_column
  major_column: r_distance_mouth_target
  max_feedback: 500
  update_every_steps: 30
  num_pretrain_frames: 30
  num_train_frames: 1000
  initialize_agent_per_session: false
  initialize_reward_model_per_session: true
  snapshot_every_n: ${rlhf.update_every_steps}
  gemini:
    model_type: gemini-1.5-pro
    target_viewpoints: ${env.query_keys}
  reset_after_rlhf: false

rlhf_replay:
  size: 500000 # too large for humanoidbench, handling recent episodes only.
  num_queries: 50
  num_labels: 1
  seq_len: 100
  feedback_batch_size: 128
  max_episode_number: 0

hydra:
  run:
    dir: ./agym_exp/state_ppo_rlhf_hybrid/agym_${env.task_name}/rlhf_hybrid_${rlhf.feedback_type}_numf${rlhf.max_feedback}_numq${rlhf_replay.num_queries}_update${rlhf.update_every_steps}_pretrain${rlhf.num_pretrain_frames}_comp-${rlhf.comparison_type}_reward-reset-${rlhf.initialize_reward_model_per_session}_agent-reset-${rlhf.initialize_agent_per_session}_lambda${reward_method.lambda_weight}_sc-${rlhf.gemini.compute_self_consistency}_sc-temp${rlhf.gemini.self_consistency_temperature}_sc-n${rlhf.gemini.n_self_consistency_samples}_seed${seed}_${now:%Y%m%d%H%M%S}
