# @package _global_

method:
  _target_: robobase.method.cqn_as_simple.CQNASSimple
  num_explore_steps: ${num_explore_steps}
  is_rl: true
  critic_lr: 1e-4
  view_fusion_lr: 1e-4
  encoder_lr: 1e-4
  weight_decay: 0.0
  num_critics: 1  # Not supported
  critic_target_tau: 0.02
  stddev_schedule: 0.1
  critic_grad_clip: null
  use_dueling: true
  always_bootstrap: false  # Always do bootstrap; could be useful for episodic task
  bc_lambda: 0.0
  bc_margin: 0.0  # If > 0.0, encourage expert action's Q(s, a*) be higher than other actions' Q(s, a)
  use_target_network_for_rollout: false
  num_update_steps: 1  # If > 1, take N updates inside a single `update` call
  use_augmentation: true
  use_torch_compile: false
  levels: 3
  bins: 5
  critic_lambda: 1.0
  critic_target_interval: 1
  centralized_critic: false
  hidden_dim: 256
  gru_layers: 0
